#############################################################################
# Makefile for building: project_joshuanl
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Feb 3 20:03:14 2015
# Project:  project_joshuanl.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile project_joshuanl.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Ilib -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Actor.cpp \
		FindBaconWindow.cpp \
		main.cpp \
		MainMenuWindow.cpp \
		NewUserWindow.cpp \
		RateMovieWindow.cpp \
		RecommendMovieWindow.cpp \
		SearchResultsWindow.cpp moc_FindBaconWindow.cpp \
		moc_MainMenuWindow.cpp \
		moc_NewUserWindow.cpp \
		moc_OpenWindow.cpp \
		moc_RateMovieWindow.cpp \
		moc_RecommendMovieWindow.cpp \
		moc_SearchResultsWindow.cpp
OBJECTS       = Actor.o \
		FindBaconWindow.o \
		main.o \
		MainMenuWindow.o \
		NewUserWindow.o \
		RateMovieWindow.o \
		RecommendMovieWindow.o \
		SearchResultsWindow.o \
		moc_FindBaconWindow.o \
		moc_MainMenuWindow.o \
		moc_NewUserWindow.o \
		moc_OpenWindow.o \
		moc_RateMovieWindow.o \
		moc_RecommendMovieWindow.o \
		moc_SearchResultsWindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		project_joshuanl.pro
QMAKE_TARGET  = project_joshuanl
DESTDIR       = 
TARGET        = project_joshuanl

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: project_joshuanl.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile project_joshuanl.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile project_joshuanl.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/project_joshuanl1.0.0 || $(MKDIR) .tmp/project_joshuanl1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/project_joshuanl1.0.0/ && $(COPY_FILE) --parents lib/Actor.h lib/FindBaconWindow.h lib/MainMenuWindow.h lib/map.h lib/MergeSort.h lib/MergeSortImp.h lib/Movie.h lib/NewUserWindow.h lib/NFDB.h lib/OpenWindow.h lib/RateMovieWindow.h lib/RecommendMovieWindow.h lib/SearchResultsWindow.h lib/User.h Movie.cpp User.cpp NFDB.cpp OpenWindow.cpp .tmp/project_joshuanl1.0.0/ && $(COPY_FILE) --parents Actor.cpp FindBaconWindow.cpp main.cpp MainMenuWindow.cpp NewUserWindow.cpp RateMovieWindow.cpp RecommendMovieWindow.cpp SearchResultsWindow.cpp .tmp/project_joshuanl1.0.0/ && (cd `dirname .tmp/project_joshuanl1.0.0` && $(TAR) project_joshuanl1.0.0.tar project_joshuanl1.0.0 && $(COMPRESS) project_joshuanl1.0.0.tar) && $(MOVE) `dirname .tmp/project_joshuanl1.0.0`/project_joshuanl1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/project_joshuanl1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_FindBaconWindow.cpp moc_MainMenuWindow.cpp moc_NewUserWindow.cpp moc_OpenWindow.cpp moc_RateMovieWindow.cpp moc_RecommendMovieWindow.cpp moc_SearchResultsWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_FindBaconWindow.cpp moc_MainMenuWindow.cpp moc_NewUserWindow.cpp moc_OpenWindow.cpp moc_RateMovieWindow.cpp moc_RecommendMovieWindow.cpp moc_SearchResultsWindow.cpp
moc_FindBaconWindow.cpp: lib/NFDB.h \
		lib/Actor.h \
		lib/User.h \
		lib/Movie.h \
		lib/FindBaconWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) lib/FindBaconWindow.h -o moc_FindBaconWindow.cpp

moc_MainMenuWindow.cpp: lib/SearchResultsWindow.h \
		lib/User.h \
		lib/Movie.h \
		lib/Actor.h \
		lib/NFDB.h \
		lib/RateMovieWindow.h \
		lib/RecommendMovieWindow.h \
		lib/FindBaconWindow.h \
		lib/MainMenuWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) lib/MainMenuWindow.h -o moc_MainMenuWindow.cpp

moc_NewUserWindow.cpp: lib/User.h \
		lib/Movie.h \
		lib/Actor.h \
		lib/NFDB.h \
		lib/NewUserWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) lib/NewUserWindow.h -o moc_NewUserWindow.cpp

moc_OpenWindow.cpp: lib/NewUserWindow.h \
		lib/User.h \
		lib/Movie.h \
		lib/Actor.h \
		lib/NFDB.h \
		lib/MainMenuWindow.h \
		lib/SearchResultsWindow.h \
		lib/RateMovieWindow.h \
		lib/RecommendMovieWindow.h \
		lib/FindBaconWindow.h \
		lib/OpenWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) lib/OpenWindow.h -o moc_OpenWindow.cpp

moc_RateMovieWindow.cpp: lib/User.h \
		lib/Movie.h \
		lib/Actor.h \
		lib/NFDB.h \
		lib/RateMovieWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) lib/RateMovieWindow.h -o moc_RateMovieWindow.cpp

moc_RecommendMovieWindow.cpp: lib/User.h \
		lib/Movie.h \
		lib/Actor.h \
		lib/NFDB.h \
		lib/RecommendMovieWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) lib/RecommendMovieWindow.h -o moc_RecommendMovieWindow.cpp

moc_SearchResultsWindow.cpp: lib/User.h \
		lib/Movie.h \
		lib/Actor.h \
		lib/NFDB.h \
		lib/SearchResultsWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) lib/SearchResultsWindow.h -o moc_SearchResultsWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Actor.o: Actor.cpp lib/Actor.h \
		lib/Movie.h \
		lib/User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Actor.o Actor.cpp

FindBaconWindow.o: FindBaconWindow.cpp lib/FindBaconWindow.h \
		lib/NFDB.h \
		lib/Actor.h \
		lib/User.h \
		lib/Movie.h \
		lib/MainMenuWindow.h \
		lib/SearchResultsWindow.h \
		lib/RateMovieWindow.h \
		lib/RecommendMovieWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FindBaconWindow.o FindBaconWindow.cpp

main.o: main.cpp Movie.cpp \
		lib/Movie.h \
		lib/User.h \
		lib/Actor.h \
		User.cpp \
		NFDB.cpp \
		lib/NFDB.h \
		OpenWindow.cpp \
		lib/OpenWindow.h \
		lib/NewUserWindow.h \
		lib/MainMenuWindow.h \
		lib/SearchResultsWindow.h \
		lib/RateMovieWindow.h \
		lib/RecommendMovieWindow.h \
		lib/FindBaconWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainMenuWindow.o: MainMenuWindow.cpp lib/MainMenuWindow.h \
		lib/SearchResultsWindow.h \
		lib/User.h \
		lib/Movie.h \
		lib/Actor.h \
		lib/NFDB.h \
		lib/RateMovieWindow.h \
		lib/RecommendMovieWindow.h \
		lib/FindBaconWindow.h \
		lib/OpenWindow.h \
		lib/NewUserWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainMenuWindow.o MainMenuWindow.cpp

NewUserWindow.o: NewUserWindow.cpp lib/NewUserWindow.h \
		lib/User.h \
		lib/Movie.h \
		lib/Actor.h \
		lib/NFDB.h \
		lib/OpenWindow.h \
		lib/MainMenuWindow.h \
		lib/SearchResultsWindow.h \
		lib/RateMovieWindow.h \
		lib/RecommendMovieWindow.h \
		lib/FindBaconWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NewUserWindow.o NewUserWindow.cpp

RateMovieWindow.o: RateMovieWindow.cpp lib/RateMovieWindow.h \
		lib/User.h \
		lib/Movie.h \
		lib/Actor.h \
		lib/NFDB.h \
		lib/MainMenuWindow.h \
		lib/SearchResultsWindow.h \
		lib/RecommendMovieWindow.h \
		lib/FindBaconWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RateMovieWindow.o RateMovieWindow.cpp

RecommendMovieWindow.o: RecommendMovieWindow.cpp lib/RecommendMovieWindow.h \
		lib/User.h \
		lib/Movie.h \
		lib/Actor.h \
		lib/NFDB.h \
		lib/MainMenuWindow.h \
		lib/SearchResultsWindow.h \
		lib/RateMovieWindow.h \
		lib/FindBaconWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RecommendMovieWindow.o RecommendMovieWindow.cpp

SearchResultsWindow.o: SearchResultsWindow.cpp lib/SearchResultsWindow.h \
		lib/User.h \
		lib/Movie.h \
		lib/Actor.h \
		lib/NFDB.h \
		lib/MainMenuWindow.h \
		lib/RateMovieWindow.h \
		lib/RecommendMovieWindow.h \
		lib/FindBaconWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SearchResultsWindow.o SearchResultsWindow.cpp

moc_FindBaconWindow.o: moc_FindBaconWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FindBaconWindow.o moc_FindBaconWindow.cpp

moc_MainMenuWindow.o: moc_MainMenuWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainMenuWindow.o moc_MainMenuWindow.cpp

moc_NewUserWindow.o: moc_NewUserWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NewUserWindow.o moc_NewUserWindow.cpp

moc_OpenWindow.o: moc_OpenWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OpenWindow.o moc_OpenWindow.cpp

moc_RateMovieWindow.o: moc_RateMovieWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RateMovieWindow.o moc_RateMovieWindow.cpp

moc_RecommendMovieWindow.o: moc_RecommendMovieWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RecommendMovieWindow.o moc_RecommendMovieWindow.cpp

moc_SearchResultsWindow.o: moc_SearchResultsWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SearchResultsWindow.o moc_SearchResultsWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

